from itertools import count, cycle
iter = count(int(input("Введите число, с которого начнется отсчет следующих 3 чисел: ")))
print(next(iter))
print(next(iter))
print(next(iter))
print(next(iter))
iter = cycle(input("Введите элементы списка для цикла через пробел: ").split())
print(next(iter))
print(next(iter))
print(next(iter))
print(next(iter))
print(next(iter))
print(next(iter))
print(next(iter))
print(next(iter))
print(next(iter))